from pathlib import Path
from version import __version__
from datetime import datetime

from models import Project, TestClass, TestFile, TestMethod
from markdown_models import ClassDocumentation, MethodDocumentation, SummaryDocumentation



class MarkdownGenerator:

    def generate(self, project: Project, output_dir: Path) -> None:

        output_dir.mkdir(parents=True, exist_ok=True)

        for test_file in project.test_files:
            for test_class in test_file.classes:

                documentation = self._create_documentation(
                    test_file,
                    test_class
                )

                markdown = self._render(documentation)

                self._write(
                    output_dir,
                    test_class,
                    markdown
                )

        self._write_index(project, output_dir)

    def _create_documentation(self, test_file: TestFile, test_class: TestClass) -> ClassDocumentation:
        methods, summary = self._collect_methods(test_class)

        nested = [
            self._create_documentation(
                test_file,
                nested_class
            ) for nested_class in test_class.nested_classes
        ]

        return ClassDocumentation(
            title=self._get_title(test_class),
            class_name=test_class.name,
            package=self._get_package(test_file),
            summary=summary,
            methods=methods,
            nested_classes=nested
        )

    def _render(self, documentation: ClassDocumentation) -> str:
        lines = []

        lines.extend(self._render_class_title(documentation))
        lines.extend(self._render_package(documentation.package))

        lines.extend(self._render_class_body(documentation, 2))

        return "\n".join(lines)

    def _write(self, output_dir: Path, test_class: TestClass, markdown: str):
        output_path = output_dir / (
            test_class.name + ".md"
        )

        output_path.write_text(markdown, encoding="utf-8")

    def _write_index(self, project: Project, output_dir: Path):
        lines = []

        lines.append("# JUnit Test Documentation")
        lines.append("")

        lines.append("## Project Summary")
        lines.append("")
        lines.append(f"- Package Count: {self._count_packages(project)}")
        lines.append(f"- Test Files: {len(project.test_files)}")
        lines.append(f"- Test Classes: {self._count_classes_from_files(project.test_files)}")
        lines.append(f"- Test Methods: {self._count_test_methods_from_files(project.test_files)}")
        lines.append(f"- Disabled Tests: {self._count_disabled_methods_from_files(project.test_files)}")
        lines.append("")

        lines.append("---\n")

        lines.append("## Packages")
        lines.append("")

        packages = self._collect_packages_and_classes(project.test_files)

        for package in packages:
            lines.append(f"### {package}")
            lines.append("")
            for entry in packages[package]:
                lines.append("\t" * entry[2] + f"- [{entry[0]}]({entry[1]})")
            lines.append("")

        lines.append("---\n")
        lines.append(f"Generated by JUnit Structure Parser v{__version__}")
        lines.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

        output_path = output_dir / (
             "index.md"
        )

        output_path.write_text("\n".join(lines), encoding="utf-8")



    def _collect_methods(self, test_class: TestClass) -> tuple[list[MethodDocumentation], SummaryDocumentation]:

        methods = []

        summary = SummaryDocumentation()

        for method in test_class.methods:

            if method.is_test:
                summary.tests+=1

                if method.is_disabled:
                    summary.disabled+=1

                if method.tags:
                    summary.tagged+=1

                methods.append(self._create_method(method))

        return methods, summary

    def _create_method(self, method: TestMethod) -> MethodDocumentation:
        return MethodDocumentation(
            title=method.display_name or method.name,
            method_name=method.name,
            tags=method.tags,
            disabled=method.is_disabled,
            location=method.location
        )

    def _get_title(self, test_class: TestClass) -> str:
        return test_class.display_name or test_class.name

    def _get_class_name(self, test_class: TestClass) -> str:
        return test_class.name

    def _get_package(self, test_file: TestFile) -> str:
        return test_file.package or "(default)"

    # -----------------
    # Render Functions
    # -----------------

    def _render_class_title(self, documentation: ClassDocumentation, level: int = 1) -> list[str]:
        lines = []

        lines.append("#" * level + " " + documentation.title)
        lines.append("")
        lines.append(f"**Class:** `{documentation.class_name}`")
        lines.append("")

        return lines

    def _render_package(self, package: str) -> list[str]:
        lines = []

        lines.append(f"## Package")
        lines.append("")
        lines.append(f"{package}")
        lines.append("")

        return lines

    def _render_summary(self, summary: SummaryDocumentation, level:int = 2) -> list[str]:
        lines = []

        lines.append("#" * (level) + " Summary")
        lines.append("")
        lines.append(f"- Tests: {summary.tests}")
        lines.append(f"- Disabled: {summary.disabled}")
        lines.append(f"- Tagged: {summary.tagged}")
        lines.append("")

        return lines

    def _render_methods(self, methods: list[MethodDocumentation], level: int = 2) -> list[str]:
        lines = []

        lines.append("#" * (level) + " Test Methods")
        lines.append("")

        for method in methods:
            lines.append("#" * (level+1) + " " + str(method.title))
            lines.append("")
            lines.append(f"- Method: `{method.method_name}`")
            lines.append(f"- Tags: {", ".join(method.tags)}")
            lines.append(f"- Disabled: {"Yes" if method.disabled else "No"}")
            lines.append(f"- Source: {
                "Unknown" if method.location is None 
                else method.location.path + ":" + str(method.location.line)}"
            )
            lines.append("")

        return lines

    def _render_class_body(self, documentation: ClassDocumentation, level: int) -> list[str]:
        lines = []

        lines.extend(self._render_summary(documentation.summary, level))

        lines.extend(self._render_methods(documentation.methods, level))

        for nested in documentation.nested_classes:

            lines.extend(self._render_class_title(nested, level))
            lines.extend(self._render_class_body(nested, level+1))

        return lines

    # -----------------
    # Project Summary Functions
    # -----------------

    def _count_packages(self, project: Project) -> int:
        return len({
            test_file.package
            for test_file in project.test_files
            if test_file.package
        })

    def _count_classes_from_files(self, files: list[TestFile]) -> int:
        total = 0

        for file in files:
            total += self._count_classes(file.classes)

        return total


    def _count_classes(self, classes: list[TestClass]) -> int:
        total = 0

        for cls in classes:

            total += 1

            total += self._count_classes(cls.nested_classes)

        return total

    def _count_test_methods_from_files(self, files: list[TestFile]) -> int:
        total = 0

        for file in files:

            total += self._count_test_methods(file.classes)

        return total

    def _count_test_methods(self, classes: list[TestClass]) -> int:
        total = 0

        for cls in classes:
            total += sum(
                1
                for method in cls.methods
                if method.is_test
            )

            total += self._count_test_methods(cls.nested_classes)

        return total

    def _count_disabled_methods_from_files(self, files: list[TestFile]) -> int:
            total = 0
    
            for file in files:
    
                total += self._count_disabled_methods(file.classes)
    
            return total

    def _count_disabled_methods(self, classes: list[TestClass]) -> int:

        total = 0

        for cls in classes:
            total += sum(
                1
                for method in cls.methods
                if method.is_test
                and method.is_disabled
            )

            total += self._count_disabled_methods(cls.nested_classes)

        return total

    def _collect_packages_and_classes(self, files: list[TestFile]) -> dict[str, list[tuple[str, str, int]]]:
        packages = {}

        for file in files:
            package = file.package or "(default)"
            package_entries = []

            packages.setdefault(package, package_entries)

            for cls in file.classes:
                self._collect_package_classes(cls, package_entries, document_name=cls.name+".md", depth=0)

        return packages

    
    def _collect_package_classes(self, test_class: TestClass, entries: list[tuple[str,str,int]],document_name: str, depth: int):
        entries.append(
            (test_class.name, document_name, depth)
        )

        for nested in test_class.nested_classes:
            self._collect_package_classes(nested, entries, document_name, depth+1)

