from datetime import datetime
from pathlib import Path
from version import __version__

class MarkdownWriter:

    def __init__(self):
        self._lines = []

    def line(self, text):
        self._lines.append(str(text))

    def paragraph(self, text):
        self._lines.append(str(text))
        self.blank_line()

    def heading (self, level: int, text):
        self.paragraph("#" * level + " " + str(text))

    def bullet(self, text, indents: int=0, ordered_number: int = 0):
        self.line("    "*indents +  f"{"-" if ordered_number == 0 else str(abs(ordered_number))+"."} " + str(text))

    def code_block(self, language: str, text):
        self.line(f"```{language}")
        self.line(str(text))
        self.paragraph("```")

    def horizontal_rule(self):
        self.paragraph("---")

    def section(self, text):
        self.line(str(text))

    def blank_line(self):
        self._lines.append("")

    def build(self) -> str:
        return "\n".join(self._lines)

    def write_to_file(self, file_name: str, output_dir: Path):
        self.horizontal_rule()
        self.line(f"Generated by JUnit Structure Parser v{__version__}")
        self.line(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

        output_path = output_dir / file_name
        output_path.write_text(self.build(), encoding="utf-8")

    def clear(self):
        self._lines = []